### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/template-rust#12]
One thing that we should probably have for all of our open source projects is a changelog, following some convention like [this](https://keepachangelog.com/en/1.0.0/). It's kind of painful, but it's good practice to have, since they make it easier for people to see what is going on, and is a good intro for new people who want to contribute, either internally or externally.

**Comment by arirawr** [comment]
That's a great idea @Jake-Shadle. Would you suggest making a CHANGELOG.md with some minor formatting? Previously I have used only GitHub releases but the link you shared advises against that.

**Comment by Jake-Shadle** [comment]
Yah, I think just putting whatever format we want as a template into the template would be fine, just to show what we recommend. And part of a version release process would be filling out an entry, and also either adding it to the github release, or just linking from the github release to the anchor for that release.

**Comment by arirawr** [comment]
Sounds good to me. Want to take that on?

**Comment by repi** [comment]
I do like the "keep a changelog" style and CHANGELOG.md, esp. with PRs editing the "Unreleased" section in it as you add stuff.

This does also connect to how we in general do releases for our crates, who does it, how often, what is included. Likely should write a small guide in our rust-ecosystem with instructions of how we should do it to keep it consistent for our crates. For example should we do a "v0.1.2" version git tags for every release together with git github release post also.

But can start with changelogs!
